#!/bin/bash
set -e
. /usr/share/debconf/confmodule

source /usr/share/maratona-flatpak-common/install_flatpak.sh

flag=1
while [ $flag -eq 1 ]; do
	packages=""
	try_install_flatpak_version "org.freedesktop.Sdk.Extension.openjdk17//21.08" \
		"39768ed35739a35cac3ac536856449f8f7c5380eeca5f4a0eba9361b7340022b" \
		|| packages=${packages}"openjdk17"

	try_install_flatpak_version "com.visualstudio.code" \
		"a3c1c20103d56d180dd30c5bdf25763520dbe0987e2ebadd96922ed109d66626" \
		|| packages=${packages}" code"

	try_install_flatpak_version "com.jetbrains.CLion" \
		"73e821684a27b04263c4640b58d84b024b9d8ce43fc31811c8534b29b9588fa1" \
		|| packages=${packages}" clion"

	try_install_flatpak_version "com.jetbrains.PyCharm-Community" \
		"1865a337afb60154cfdf6a15dc5a804109575d6666c63b314db17b4fc0810991" \
		|| packages=${packages}" pycharm-community"

	try_install_flatpak_version "com.jetbrains.IntelliJ-IDEA-Community" \
		"88886971f609aa69ea8fc9082bcde06a0671a3ed6126733981380a16adbd4bba" \
		|| packages=${packages}" intellij-idea-community"

	if [ "${packages}" != "" ]; then
		db_subst maratona-editores-flatpak/question_try_again package "${packages}" || true
		db_input high maratona-editores-flatpak/question_try_again || true
		db_go || true
		db_get maratona-editores-flatpak/question_try_again || true
		if [ "$RET" == "Later" ]; then
			flag=0
			db_input high maratona-editores-flatpak/notice || true
			db_go || true
			db_get maratona-editores-flatpak/notice
		fi
	else
		flag=0
	fi
done
